# Generated by Django 4.2.7 on 2023-12-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Getting Ready', 'Getting Ready'), ('On the Way', 'On the Way'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
