# Generated by Django 4.2.7 on 2024-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Base', 'Base'), ('Lentil', 'Lentil'), ('Veggie', 'Veggie'), ('Protein', 'Protein'), ('Pickle', 'Pickle')], default='Base', max_length=20),
        ),
        migrations.AddField(
            model_name='dish',
            name='portion',
            field=models.DecimalField(decimal_places=2, default=256, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images'),
        ),
    ]
