# Generated by Django 4.2.7 on 2023-12-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customorder_dish_customorderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Method', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='customorderlist',
            name='CustomOrderID',
        ),
        migrations.RemoveField(
            model_name='customorderlist',
            name='DishID',
        ),
        migrations.DeleteModel(
            name='CustomOrder',
        ),
        migrations.DeleteModel(
            name='CustomOrderList',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
