# Generated by Django 4.2.7 on 2023-12-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.IntegerField(),
        ),
    ]
