# Generated by Django 4.2.7 on 2023-12-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_address_customer_remove_address_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(default=1234567890, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
