# Generated by Django 4.2.7 on 2024-02-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_rename_phonenumber_customer_phone_number_and_more'),
        ('subscriptions', '0002_subscriptiondeliverydetails_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondeliverydetails',
            name='delivery_address',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='authentication.address'),
        ),
    ]
